# Generated by Django 4.2.9 on 2024-01-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='fgthh', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
